# Generated by Django 5.2.6 on 2025-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='services/types/')),
            ],
            options={
                'verbose_name': 'Loại dịch vụ',
                'verbose_name_plural': 'Các loại dịch vụ',
            },
        ),
    ]
