# Generated by Django 5.2.6 on 2025-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã DV')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Dịch vụ')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['service_id'],
            },
        ),
    ]
