# Generated by Django 5.2.6 on 2025-11-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.IntegerField(default=99, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp (Ẩn)'), ('published', 'Công khai (Hiện)'), ('archived', 'Lưu trữ')], default='draft', max_length=10, verbose_name='Trạng thái hiển thị'),
        ),
    ]
